apiVersion: v1
kind: Service
metadata:
  name: academic-spl-service
  namespace: academic-spl
  labels:
    app: academic-spl
spec:
  type: LoadBalancer  # GCP asigna una IP pública automáticamente
  selector:
    app: academic-spl
  ports:
  - name: http
    port: 80
    targetPort: 8000  # Puerto de FastAPI/uvicorn
