apiVersion: v1
kind: Service
metadata:
  name: academic-spl-service
  namespace: academic-spl
  labels:
    app: academic-spl
spec:
  type: ClusterIP  # Solo accesible internamente por el Frontend (ahorra cuota de IPs)
  selector:
    app: academic-spl
  ports:
  - name: http
    port: 80
    targetPort: 8000  # Puerto de FastAPI/uvicorn
